---
- block:
    - apt:
        name:
          - xbindkeys
          - xdotool
          - xcape
        state: present
        update_cache: yes
  become: yes
  become_user: root

- name: copy xmodmap file to ~/.xmodmap
  copy:
    src: "{{ role_path }}/files/xmodmap"
    dest: ~/.xmodmap

- name: enable caps with xcape as single key and for combination
  lineinfile:
    path: ~/.profile
    line: "xcape -e 'Mode_switch=Escape'"