interception:
  hosts:
    localhost:
      become: false
      connection: local
      ansible_user: "{{ lookup('env', 'USER')}}"
      vars:
        LINK: /dev/input/by-path/platform-i8042-serio-0-event-kbd

# zsh:
#   hosts:
#     localhost:
#       become: false
#       connection: local
#       ansible_user: "{{ lookup('env', 'USER')}}"