---

# Both jobs do not work toegether
# - JOB: "intercept -g $DEVNODE | caps2esc | uinput -d $DEVNODE"
#   DEVICE:
#     LINK: "{{ LINK }}"
#     EVENTS:
#       EV_KEY: [ KEY_CAPSLOCK, KEY_ESC ]

- JOB: "intercept -g $DEVNODE | dual-function-keys -c /etc/interception/dual_function_keys.yaml | uinput -d $DEVNODE"
  DEVICE:
    LINK: "{{ LINK }}"
    EVENTS:
      EV_KEY: [ KEY_RIGHTSHIFT ]