---
- name: set script to use better open dialog
  copy:
    content: |
      #!/bin/bash
      # after sleep does not work
      export GTK_USE_PORTAL=0
    dest: ~/.config/plasma-workspace/env/makeportal.sh
    mode: 500