---
- block:
    - apt:
        name:
          - cmake
          - libevdev-dev
          - libudev-dev
          - libyaml-cpp-dev
          - libboost-dev
          - xdotool
          - wmctrl
        state: present
        update_cache: yes
  become: true
  become_user: root
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'

- block:
    - pacman:
        name:
          - cmake
          - libevdev-devel
          - libudev
          - yaml-cpp
          - boost-libs
          - xdotool
          - wmctrl
        state: present
        update_cache: yes
      when: ansible_facts['distribution'] == 'Arch Linux'
  become: true
  become_user: root

- name: clone interception and build
  shell:
    executable: /bin/bash
    cmd: |
      set -ex
      src=/usr/local/src/interception
      test -d "$src" && rm -Rf "$src"
      git clone https://gitlab.com/interception/linux/tools.git "$src"
      cd "$src"
      cmake -B build -DCMAKE_BUILD_TYPE=Release
      cmake --build build

      rm /usr/local/bin/{mux,intercept,udevmon,uinput} -Rf || true
      cp build/{mux,intercept,udevmon,uinput} /usr/local/bin
  when: false

- name: make udevmon.d
  file:
    state: directory
    path: /etc/interception/udevmon.d
    recurse: yes
    owner: root

- name: install service
  template:
    src: "{{ role_path }}/files/udevmon.service"
    dest: /etc/systemd/system
    owner: root
    group: root

- systemd:
    name: udevmon
    state: started
    enabled: yes

- name: clone dual function keys and build
  shell:
    executable: /bin/bash
    cmd: |
      set -ex
      src=/usr/local/src/interception_dual_function_keys
      test -d "$src" && rm -Rf "$src"
      git clone https://gitlab.com/interception/linux/plugins/dual-function-keys "$src"
      cd "$src"
      make
      make install

- name: clone interception-vimproved
  shell:
    executable: /bin/bash
    cmd: |
      set -ex
      src=/usr/local/src/interception_vimproved
      test -d "$src" && rm -Rf "$src"
      git clone https://github.com/maricn/interception-vimproved "$src"
      cd "$src"
      make
      make install

# - name: clone karabiner s+jhkl
#   shell:
#     executable: /bin/bash
#     cmd: |
#       set -ex
#       src=/usr/local/src/interception_shjkl
#       test -d "$src" && rm -Rf "$src"
#       git clone https://github.com/kbairak/s2arrows "$src"
#       cd "$src"
#       cmake -B build -DCMAKE_BUILD_TYPE=Release
#       cmake --build build
#       cp build/s2arrows /usr/local/bin


# - name: setup choreded keymap
#   shell:
#     executable: /bin/bash
#     cmd: |
#       set -ex
#       src=/usr/local/src/interception_dual_function_keys
#       test -d "$src" && rm -Rf "$src"
#       git clone https://gitlab.com/interception/linux/plugins/dual-function-keys "$src"
#       cd "$src"
#       make
#       make install


- name: clone caps2esc and compile
  shell:
    executable: /bin/bash
    cmd: |
      set -ex
      src=/usr/local/src/interception_caps2esc
      test -d "$src" && rm -Rf "$src"
      git clone https://gitlab.com/interception/linux/plugins/caps2esc "$src"
      cd "$src"
      git submodule update --init
      cmake -B build -DCMAKE_BUILD_TYPE=Release
      cmake --build build
      cp build/caps2esc /usr/local/bin

- name: copy right_shift to /etc/interception/udevmon.d/jobs.yaml
  template:
    src: "{{ role_path }}/files/jobs.yaml"
    dest: /etc/interception/udevmon.d/jobs.yaml

- name: copy dual_function_keys to /etc/interception/dual_function_keys.yaml
  copy:
    src: "{{ role_path }}/files/dual_function_keys.yaml"
    dest: /etc/interception/dual_function_keys.yaml

- debug:
    var: vars